spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/hw_9
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
